### ISSUE TITLE
Interactive Push Notifications? (iOS8+)

### ISSUE THREAD

**Issue by yozef** [Plotprojects/plot-titanium-module#1]
I wonder if it is possible to have Actionable/Interactive Push Notifications, in order to set a CATEGORY param to the Push, and handle the Push Actions via the App?

**Comment by ygbr** [comment]
+1 for this... Ti already support categories for iOS 8 running on Ti SDK 4.0.0.GA :)

**Comment by yozef** [comment]
@ygbr You can actually Filter your notifications, and create you own Local Push (after 1 second) with Categories for Actionable Push Notifications.
