### ISSUE TITLE
Plot update to Titanium module for iOS 13

### ISSUE THREAD

**Issue by yozef** [Plotprojects/plot-titanium-module#12]
Given that iOS 13 has some changes on how location permissions occur, is there any updates required from the Titanium Module?

**Comment by markvandertol** [comment]
Hi Yosef,

iOS 13 indeed changes the location permissions behind the scenes. However, it doesn't change the api for the permissions. Therefore, no change is needed to the module.

For a background on what changes for the user, you could read our blogpost: https://www.plotprojects.com/blog/ios13-location-opt-in-your-questions-answered/
