### ISSUE TITLE
Android module 1.15.4 needs to be recompiled for Ti SDK >= 6.x

### ISSUE THREAD

**Issue by yozef** [Plotprojects/plot-titanium-module#5]
The current module needs to be recompiled for Ti >= 6.x

http://www.appcelerator.com/blog/2016/11/ga-releases-for-6-0-0-of-sdk-cli-4-8-0-of-studio/

http://skypanther.com/2016/10/rebuilding-modules-for-titanium-6/

**Comment by markvandertol** [comment]
Thank you for reporting this. We will look into this.

**Comment by yozef** [comment]
Hi Mark,
Any updates? We're kind of blocked.

**Comment by markvandertol** [comment]
We're looking into this, but we run into some problems. For example the compilation scripts we use no longer work as expected. Also in that part was a breaking change. We schedule it to fix this issue soon, but I cannot give you an exact date.

**Comment by yozef** [comment]
Was easy...
[com.plotprojects.ti-android-1.15.5.zip](https://github.com/Plotprojects/plot-titanium-module/files/763759/com.plotprojects.ti-android-1.15.5.zip)

All you need to do is update your SDK to 6.x

in manifest:
```
version: 1.15.5
apiversion: 3 // bump to 3
...
architectures: armeabi-v7a x86 // remove armeabi
...
minsdk: 6.0.0.GA
```

then build with `appc run --build-only` from within `android/` folder

**Comment by markvandertol** [comment]
Thank you for sharing this with us. We'll have a look at this.

**Comment by markvandertol** [comment]
With our latest release (1.15.5), the issue has been resolved. Now we properly support Titanium 6.
