### ISSUE TITLE
plotNotificationReceived event not working on iOS 11 after adding another module

### ISSUE THREAD

**Issue by rpenates** [Plotprojects/plot-titanium-module#6]
Hi, 
I've found an issue with the "plotNotificationReceived" event on iOS 11 after adding another module with notifications, specifically Puhswoosh module. 
When another module is added to the app (pushwoosh) the geotriggered notifications are still appearing and when the user taps the notification the event listener is not responding leading to no action in the app.
In several test i've found that after deactivate pushwoosh module the behavior is the expected or running the app in a device with iOS 9 or 10 both modules works fine in the app, also i tried with diferents versions of them. 

I made a basic titanium app to reproduce the issue, to run properly you will need a valid public token from plotprojects, some active geofences to trigger notifications, a valid appid from pushwoosh and a google project id (this one is optional).

Here is the link: https://github.com/rpenates/plot-projects_test

Affected PlotProjects module versions:
- iphone-2.0.0
- iphone-1.15.5

Pushwoosh version:
- 3.4 and above

**Comment by pastuxso** [comment]
@rpenates could you please provide the link with the code of the pushwoosh module?

**Comment by rpenates** [comment]
@pastuxso of course, here is: https://github.com/Pushwoosh/pushwoosh-appcelerator-titanium

**Comment by KalliopiNikitopoulou** [comment]
@rpenates Thanks for pointing out this issue. We are working on it at the moment.

**Comment by KalliopiNikitopoulou** [comment]
@rpenates Although our plugin has the functionality in place to work with another module when that is also using the UNUserNotificationCenter, this seems to not work as expected with Pushwoosh. Specifically, the didReceiveNotificationResponse method of the UNUserNotificationCenter is not forwarded properly. Looking at the source code of the Appcelerator code of Pushwoosh confirms this: https://github.com/Pushwoosh/pushwoosh-appcelerator-titanium/blob/5.4.1/Module-Source/ios/Classes/ComPushwooshModuleModule.m#L62 This isn't something we can easily fix from our side.

**Comment by markvandertol** [comment]
As it isn't a direct issue with our SDK, I'm closing this ticket.
