### ISSUE TITLE
Unable to build android app that uses both Plot 2.1.0 and ti.map modules

### ISSUE THREAD

**Issue by adampax** [Plotprojects/plot-titanium-module#8]
- Titanium SDK: 6.2.2 and 6.3.0
- Titanium CLI: 5.0.14
- Node.js: 8.6.0
- MacOS: 10.12.6
- Plot module version: android-2.1.0
- ti.map module version: 3.3.1 (latest that supports Ti SDK 6.x)
- Android SDK Build tool versions tested: 23.0.3 and 27.0.3

When I try to build a titanium android app that contains both Plot module 2.1.0 and ti.map, I receive the following error at compile:

```
 ...
[WARN]  Overwriting XML node common_google_play_services_unknown_issue in file /Users/adam/Dev/scratch/plot-titanium-module/plotprojects-example/build/android/res/values-zh-rTW/values-zh-rTW.xml
[WARN]  Overwriting XML node common_google_play_services_unknown_issue in file /Users/adam/Dev/scratch/plot-titanium-module/plotprojects-example/build/android/res/values-zu/values-zu.xml
[INFO]  No aidl files to compile, continuing
[INFO]  Generating i18n files
[INFO]  Generating /Users/adam/Dev/scratch/plot-titanium-module/plotprojects-example/build/android/res/values/theme.xml
[INFO]  Running AAPT: /Users/adam/Library/Android/sdk/build-tools/27.0.3/aapt "package" "-f" "-m" "-J" "/Users/adam/Dev/scratch/plot-titanium-module/plotprojects-example/build/android/gen" "-M" "/Users/adam/Dev/scratch/plot-titanium-module/plotprojects-example/build/android/AndroidManifest.xml" "-A" "/Users/adam/Dev/scratch/plot-titanium-module/plotprojects-example/build/android/bin/assets" "-S" "/Users/adam/Dev/scratch/plot-titanium-module/plotprojects-example/build/android/res" "-I" "/Users/adam/Library/Android/sdk/platforms/android-26/android.jar" "-F" "/Users/adam/Dev/scratch/plot-titanium-module/plotprojects-example/build/android/bin/app.ap_" "--output-text-symbols" "/Users/adam/Dev/scratch/plot-titanium-module/plotprojects-example/build/android/intermediates/bundles" "--no-version-vectors" "--auto-add-overlay" "--extra-packages" "ti.modules.titanium.ui:android.support.v7.appcompat:android.support.v7.cardview:android.support.design:android.support.compat:com.google.android.gms"
[ERROR] Failed to package application:
[ERROR]
[ERROR] /Users/adam/Dev/scratch/plot-titanium-module/plotprojects-example/build/android/res/drawable-hdpi-v4/common_full_open_on_phone.png: error: Duplicate file.
[ERROR] /Users/adam/Dev/scratch/plot-titanium-module/plotprojects-example/build/android/res/drawable-hdpi/common_full_open_on_phone.png: Original is here. The version qualifier may be implied.
```
I am testing with the `plotprojects-example` example app located in this repo. After adding the plot module to the app, I then add the following to `tiapp.xml`:

```
<module platform="android">ti.map</module>
```

If I remove the ti.map reference, it builds without issue.

**Comment by andrebsampaio** [comment]
Hi Adam,
This issue is related to a conflict between the google play services dependency version used in the ti.map and in our plugin. To solve this, include the ti.map 3.3.1 manually (via [Github repo](https://github.com/appcelerator-modules/ti.map/releases/download/android-3.3.1/ti.map-android-3.3.1.zip)) and remove the folder `ti.map/3.3.1/platform/android/res` and the dependencies `google-play-services-base.jar` and `google-play-services-base.jar` present in the `ti.map/3.3.1/lib` folder, as this is already included in our plugin. We use google play services version 11.6.0 which is more recent than the one used in ti.map (11.0.4).

**Comment by adampax** [comment]
Working for me now, thanks.  I also had to remove `google-play-services-base.jar`.
